apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mho3a16t4-python 
  janus-idp.io/tekton: mho3a16t4-python
  backstage.io/kubernetes-id: mho3a16t4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mho3a16t4-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml