apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mho3a16t4-python
  janus-idp.io/tekton: mho3a16t4-python
  backstage.io/kubernetes-id: mho3a16t4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mho3a16t4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
